version: '3.8'
services:
  app:
    image: dlsapi:0.1
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
    - ./backend:/home/user/app/backend
    ports:
    - "8000:8000"
    links:
      - db
  db:
    image: postgis/postgis
    restart: on-failure
    volumes:
      - .db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=djlinkshortner
      - POSTGRES_PASSWORD=djlinkshortner@123
      - POSTGRES_DB=djlinkshortner

