# Generated by Django 3.0.8 on 2020-07-05 18:40

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200705_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.get_profile_pic_path),
        ),
    ]
