# Generated by Django 2.2.14 on 2020-07-22 10:21

from django.db import migrations, models
import utils.link_code_generator


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20200721_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='deep_link',
            field=models.URLField(default='https://google.in/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='keyword',
            field=models.CharField(default=utils.link_code_generator.get_link_code, help_text='Unique keywork for the link', max_length=10, unique=True),
        ),
    ]
